# Generated by Django 5.1 on 2024-09-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salida', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsalida',
            name='descriptions',
            field=models.CharField(max_length=500),
        ),
    ]
