# Generated by Django 5.1 on 2024-09-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_rename_order_postregistro_cantidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postregistro',
            old_name='fecha',
            new_name='fecha_salida',
        ),
        migrations.AlterField(
            model_name='postregistro',
            name='categoria',
            field=models.CharField(max_length=500),
        ),
    ]
